// ParentPrep — the four trip scenarios.
// Two ages (3 months, 6 months) × two trip lengths (short, long).
// Edit freely — this is the file to refine with your parenting group.
window.TEMPLATES = [

  {
    id: "short-3mo",
    age: "3 months old",
    name: "Short trip",
    emoji: "🚗",
    description: "Store run or drive under an hour",
    items: [
      "Infant car seat",
      "Car seat cover / blanket",
      "3 diapers",
      "Travel wipes pack",
      "Changing pad",
      "Disposable bag for dirty diaper",
      "Spare onesie",
      "Spare swaddle / muslin",
      "2 burp cloths",
      "Bottle OR nursing cover",
      "Pacifier",
      "Small soft toy / rattle",
      "Hand sanitizer",
      "Hat",
      "Stroller or carrier",
      "Phone (charged)",
    ],
  },

  {
    id: "long-3mo",
    age: "3 months old",
    name: "Long trip",
    emoji: "✈️",
    description: "5+ hour drive or flight",
    items: [
      "Infant car seat",
      "Stroller (gate-check if flying)",
      "Baby carrier (hands-free at airport)",
      "Diapers — at least 10",
      "Full wipes pack + travel pack",
      "Changing pad",
      "Diaper rash cream",
      "Disposable bags for dirty diapers",
      "3-4 outfits (blowouts happen)",
      "4 burp cloths",
      "3-4 muslin swaddles",
      "Sleep sack",
      "2 pacifiers (ear pressure on takeoff/landing)",
      "Formula pre-measured OR pump + bottles + cooler",
      "Extra bottles",
      "Bottled water for formula",
      "Nursing cover",
      "Nursing pads",
      "Small rattle or soft toy",
      "Baby Tylenol (check with pediatrician first)",
      "Thermometer",
      "Birth certificate (required for infant flights)",
      "Health insurance card",
      "Change of shirt for BOTH parents",
      "Hand sanitizer",
      "Disinfecting wipes (tray tables, hotel surfaces)",
      "Weather layers + hat",
      "Sunshade for car window",
    ],
  },

  {
    id: "short-6mo",
    age: "6 months old",
    name: "Short trip",
    emoji: "🚗",
    description: "Store run or drive under an hour",
    items: [
      "Car seat",
      "3 diapers",
      "Travel wipes",
      "Changing pad",
      "Disposable bags for dirty diapers",
      "Spare outfit",
      "Bib",
      "Burp cloth",
      "Bottle / sippy cup with water",
      "Food pouch or puffs",
      "Spoon (if needed)",
      "Small teether toy",
      "Pacifier (if used)",
      "Sunhat",
      "Sunscreen (6m+ approved)",
      "Hand sanitizer",
      "Stroller or carrier",
      "Phone (charged)",
    ],
  },

  {
    id: "long-6mo",
    age: "6 months old",
    name: "Long trip",
    emoji: "✈️",
    description: "5+ hour drive or flight",
    items: [
      "Car seat (installed or gate-checked)",
      "Stroller",
      "Baby carrier",
      "Diapers — at least 10",
      "Full wipes pack + travel pack",
      "Changing pad",
      "Diaper cream",
      "Disposable bags",
      "3-4 outfits",
      "3-4 bibs",
      "Burp cloths",
      "Muslin swaddles",
      "Sleep sack",
      "Pacifiers",
      "Bottles + formula OR pump gear",
      "Sippy cup with water",
      "Food pouches (multiple flavors)",
      "Baby spoons",
      "Puffs / teething biscuits",
      "Snack catcher / small container",
      "Teethers",
      "Small toys (rotate to keep novel)",
      "Crinkle books / soft books",
      "Sunhat",
      "Sunscreen (6m+)",
      "Baby Tylenol + Ibuprofen (6m+)",
      "Thermometer",
      "Birth certificate (if flying)",
      "Insurance card",
      "Hand sanitizer",
      "Disinfecting wipes",
      "Change of shirt for parents",
      "Weather layers",
    ],
  },

];
